### PR TITLE
Add Import for Kreisparkasse and Volksbank

### PR DESCRIPTION
**Pull request by jHetzer**
Add Import for Kreisparkasse and Volksbank.
Fix formating typos (whitespaces and tabs)

### CODE REVIEW

**Comment by lasalesi** [comment]
Hi @jHetzer,
thank you for this pull-request.

Did you also want to include the enabling/disabling of the formats from the settings?

**Comment by jHetzer** [comment]
I will develop it as soon as possible :). For the screenshots I used a child table doctype. I see two options:
1. Hard coding the banks in ERPNextSwiss Settings DocType, Python and JavaScript file
or
2. Create a Child Table Doctype + Templating DocTypes as in the screenshots. A simple form of CSV Templating (direct column / field mapping) would be required because admins could possibly add custom banks.

The second option would require to add a setup script which would create the default bank settings/DocTypes.

I would personally prefer the second option and later extent the templating functionality.

**Comment by lasalesi** [comment]
I also like option two, but would implement it with
* add child DocType "ERPNextSwiss Settings Bank" (or similar) as `banks`
* we could populate this in case has `banks` 0 rows with the default settings (or use a setup script, but this might not work in case this is updated on a previously installed system)
* conditionally load this in the bank import page

Templating could always be introduced at a later stage...

**Comment by jHetzer** [comment]
Supersede by https://github.com/libracore/erpnextswiss/pull/56

**Pull request closed without merging**
